---
title: "Process Sub"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(ggspatial)
library(lubridate)
library(bdc)

ps_data_path <- "/Volumes/ps-science/datasets/"

ps_exp_path <- "/Volumes/Colombia - 2022/"

default_font_family <- "Arial"

default_font_color <- '#22211d'

default_background_color <- "#f5f5f2"

load(file = file.path(ps_exp_path, "data", "secondary", "processed", "admin_spatial_layers.RData"))

theme_map <- function(...) {
  theme_minimal() +
    theme(
      text = element_text(family = default_font_family,
                          color = default_font_color),
      # remove all axes
      # add a subtle grid
      panel.grid.major = element_line(color = "#dbdbd9", size = 0.2),
      panel.grid.minor = element_blank(),
      # background colors
      plot.background = element_rect(fill = default_background_color,
                                     color = NA),
      panel.background = element_rect(fill = default_background_color,
                                      color = NA),
      legend.background = element_rect(fill = default_background_color,
                                       color = NA),
      # borders and margins
      plot.margin = unit(c(.5, .5, .2, .5), "cm"),
      panel.border = element_blank(),
      panel.spacing = unit(c(-.1, 0.2, .2, 0.2), "cm"),
      # titles
      legend.title = element_text(size = 11),
      legend.text = element_text(size = 9, hjust = 0,
                                 color = default_font_color),
      plot.title = element_text(size = 15, hjust = 0.5,
                                color = default_font_color),
      plot.subtitle = element_text(size = 10, hjust = 0.5,
                                   color = default_font_color,
                                   margin = margin(b = -0.1,
                                                   t = -0.1,
                                                   l = 2,
                                                   unit = "cm"),
                                   debug = F),
      # captions
      plot.caption = element_text(size = 7,
                                  hjust = .5,
                                  margin = margin(t = 0.2,
                                                  b = 0,
                                                  unit = "cm"),
                                  color = "#939184"),
      ...
    )
}
```

# Metadata

```{r}
sub_meta <- readxl::read_excel(file.path(ps_exp_path, 
                                        "data", "primary","raw","sub","_COL_sub_metadata.xlsx")) %>% 
  janitor::clean_names() 

date(sub_meta$dive_start) <- sub_meta$date
date(sub_meta$resurface) <- sub_meta$date
date(sub_meta$bottom_time) <- sub_meta$date
sub_meta$therm_end <- as.numeric(sub_meta$therm_end)
sub_meta$therm_start <- as.numeric(sub_meta$therm_start)

sub_meta$bottom_time <- lubridate::as.difftime(format(sub_meta$bottom_time, "%H:%M:%S"),
                                               units = "hours")

sub_meta <- sub_meta %>% 
  mutate(location = if_else(date < ymd("2022-03-15"), "Yurupari ridge", 
                       if_else(date < ymd("2022-03-30"), "Golfo de Tribuga", 
                               "Caribe")),
         sublocation = if_else(date < ymd("2022-03-15"), "Navigator bank", 
                       if_else(date < ymd("2022-03-30"), "Golfo de Tribuga", 
                               "Bajo Nuevo")))
```

```{r}
bottom_start_coords <- sub_meta$gps_bottom_start %>%
  str_split("N", simplify = T) %>% 
  as_tibble() %>% 
  select(bottom_start_lat = V1,  bottom_start_lon = V2) %>% 
  mutate_all(str_remove, pattern = c("W")) %>% 
  mutate_all(str_squish) %>% 
  mutate_all(str_replace_all, pattern = "\\'", replacement =  " ") %>% 
  mutate_all(measurements::conv_unit, from = 'deg_dec_min', to = 'dec_deg') %>% 
  mutate_all(as.numeric) %>% 
  mutate(bottom_start_lon =  -1*bottom_start_lon) %>% 
  mutate_all(round, 5)

bottom_end_coords <- sub_meta$gps_bottom_end %>%
  str_split("N", simplify = T) %>% 
  as_tibble() %>% 
  select(bottom_end_lat = V1,  bottom_end_lon = V2) %>% 
  mutate_all(str_remove, pattern = c("W")) %>% 
  mutate_all(str_squish) %>% 
  mutate_all(str_replace_all, pattern = "\\'", replacement =  " ") %>% 
  mutate_all(measurements::conv_unit, from = 'deg_dec_min', to = 'dec_deg') %>% 
  mutate_all(as.numeric) %>% 
  mutate(bottom_end_lon =  -1*bottom_end_lon) %>% 
  mutate_all(round, 5)

sub_meta <- sub_meta %>% 
  select(ps_station_id, location, sublocation, date, dive_start, dive_end = resurface, bottom_time,
         max_depth, therm_start_depth = therm_start, therm_end_depth = therm_end, 
         temp_at_max_depth = max_depth_temp, deepsee_dive_number) %>% 
  bind_cols(bottom_start_coords) %>% 
  bind_cols(bottom_end_coords)
```

```{r}
write_csv(sub_meta, file.path(ps_exp_path, "data", "primary", "processed", "sub_meta.csv"))

sub_meta %>% 
  sf::st_as_sf(coords = c("bottom_start_lon","bottom_start_lat"), 
               crs = 4326) %>% 
  st_transform(crs = col_crs) %>% 
  st_write(file.path(ps_exp_path, "data", "primary", "processed",  "sub_meta.gpkg"), append = F)
```

# Taxa list

```{r}
navi_taxa <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                             "sub", "files/navigator_sub_taxa_lut.xlsx")) %>% 
  janitor::clean_names() %>% 
  distinct(taxon,nombre_comun, is_vme)

bn_taxa <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/bajo_nuevo_annotations.xlsx"),
                  sheet = "observations") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(taxa)) %>% 
  distinct(taxa)
```

```{r}
sub_taxa <- bdc::bdc_clean_names(c(bn_taxa$taxa, navi_taxa$taxon)) %>% 
  janitor::clean_names() %>% 
  select(taxon = scientific_name, 
         taxon_clean = names_clean) %>% 
  mutate(taxon_clean = coalesce(taxon_clean, 
                               taxadb::clean_names(taxon, lowercase = F))) %>% 
  distinct(taxon, taxon_clean)

sub_taxa$taxon_clean[sub_taxa$taxon == "CCA"] <- "Florideophyceae"

sub_taxa %>% 
  filter(taxon != taxon_clean)
```

```{r}
gbif_resolved_names <- bdc_query_names_taxadb(sub_taxa$taxon_clean,
                                            replace_synonyms = TRUE,
                                            suggest_names = TRUE,
                                            suggestion_distance = 0.8,
                                            db = "gbif",
                                            parallel = TRUE,
                                            ncores = 2,
                                            export_accepted = FALSE) %>% 
  janitor::clean_names()


gbif_resolved_names <- gbif_resolved_names %>% 
  mutate(resolved_sci_name = coalesce(scientific_name, original_search)) %>% 
  distinct(original_search, resolved_sci_name) %>% 
  rename("taxon_clean" = "original_search")

sub_taxa <- sub_taxa %>% 
  left_join(gbif_resolved_names) %>% 
  select(-taxon_clean)

length(unique(sub_taxa$resolved_sci_name))
```


```{r}
sub_taxa_resolved <- worrms::wm_records_names(sub_taxa$resolved_sci_name) %>%  
  bind_rows() %>% 
  janitor::clean_names() %>%
  filter(kingdom != "Chromista") %>% 
  select(resolved_sci_name = scientificname,  rank, valid_name, valid_aphia_id, 
           valid_authority, kingdom, phylum, class, order, family, genus) %>% 
  distinct()

sub_taxa_resolved %>% 
  filter(valid_name != resolved_sci_name)
```

```{r}
sub_taxa_resolved <- sub_taxa %>% 
  left_join(sub_taxa_resolved %>% 
              select(-valid_name))

sub_taxa_resolved %>% 
  group_by(phylum) %>% 
  summarize(n())
```

## is vme

```{r}
all_vme_taxa <- read_csv(file.path(ps_data_path, "VMEs", "files", "all_vme_taxa.csv"))
vme_ind <- read_csv(file.path(ps_data_path, "VMEs", "files", "clean_vme_ind.csv"))

sub_taxa_resolved <- sub_taxa_resolved %>% 
  mutate(is_vme = if_else(valid_aphia_id %in% 
                            c(vme_ind$valid_aphia_id, all_vme_taxa$valid_AphiaID), T, F))

sub_taxa_resolved %>% 
  filter(is_vme)
```

```{r}
sub_taxa_resolved %>%
  write_csv(file.path(ps_exp_path, "data", "secondary", "processed", "sub_taxa_resolved.csv"))
```

## is threatened

```{r}
iucn_db <- read_csv(file.path(ps_data_path, 
                                       "iucn-redlist-marine-species",  "joined_and_resolved_taxa.csv")) %>% 
  mutate(valid_aphia_id = as.numeric(str_remove_all(string = taxon_id, "WORMS:")))
  

sub_taxa_resolved %>% 
  left_join(iucn_db %>% 
              filter(!is.na(valid_aphia_id)) %>% 
              distinct(valid_aphia_id, redlistCategory, populationTrend), 
            by = "valid_aphia_id") 
  
```

# Analyses

## DACOR - Navigator

```{r}
dacor_to_num <- function(dacor){
  
  dacor[dacor == "R"] <- 1
  dacor[dacor == "O"] <- 2
  dacor[dacor == "C"] <- 3
  dacor[dacor == "A"] <- 4
  dacor[dacor == "D"] <- 5
  dacor[is.na(dacor)] <- 0
  
  dacor <- round(as.numeric(dacor), 2)
  return(dacor)
  
}

num_to_dacor <- function(dacor_num){
  
  dacor_num[dacor_num > 4 & dacor_num <= 5] <- "D"
  dacor_num[dacor_num > 3 & dacor_num <= 4] <- "A"
  dacor_num[dacor_num > 2 & dacor_num <= 3] <- "C"
  dacor_num[dacor_num > 1 & dacor_num <= 2] <- "O"
  dacor_num[dacor_num <= 1] <- "R"
  
  dacor_cat <- as.character(dacor_num)
  
  return(dacor_cat)
  
}
```

```{r}
navi_habs_lut <- read_csv(file.path(ps_exp_path, "data/primary/raw",
                                             "sub", "files/navigator_sub_habitat_lut.csv")) %>% 
  janitor::clean_names()
```

```{r}
navi_taxa %>% 
  left_join(sub_taxa_resolved) %>% 
  group_by(phylum) %>% 
  summarize(n_taxa = n_distinct(taxon))
```
### Rocky Walls

```{r}
rocky_walls <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub", "files/navigator_annotations_sala_friedlander.xlsx"),
                                    sheet = "rocky walls")       

rocky_walls <- rocky_walls %>%                                              
  select(taxon, COL_sub_02 = "dive 2") %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  mutate(habitat = "rocky walls",
         dacor_num = dacor_to_num(dacor)) 

janitor::get_dupes(rocky_walls, "taxon")

rocky_walls_dacor <- rocky_walls %>% 
  left_join(sub_taxa_resolved, by = "taxon") %>% 
  select(ps_station_id, habitat, phylum, taxon,  dacor, dacor_num) %>% 
  arrange(desc(dacor_num))
```

### Hard bottom

```{r}
hard_bottom_ES_AF <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub", "files/navigator_annotations_sala_friedlander.xlsx"),
                  sheet = "hard bottom") %>% 
  select(taxon, COL_sub_02 = "dive 2", COL_sub_03 = "dive 3") %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "hard bottom") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)

hard_bottom_JM <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/navigator_annotations_mayorga.xlsx"), 
                                    sheet = "hard bottom") %>% 
  select(taxon, COL_sub_04 = "dive 4") %>% 
  filter(!is.na(COL_sub_04)) %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "hard bottom") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)

hard_bottom_dacor <- hard_bottom_JM %>% 
  bind_rows(hard_bottom_ES_AF) %>% 
  arrange(desc(dacor_num))
```

```{r}
hard_bottom_dacor %>% 
  group_by(taxon) %>% 
  summarize(overall_dacor_num = mean(dacor_num)) %>% 
  mutate(overall_dacor = num_to_dacor(overall_dacor_num))
```

### Sand with pebbles

```{r}
sand_and_pebbles <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub", "files/navigator_annotations_sala_friedlander.xlsx"), 
                                      sheet = "sand with pebbles") %>% 
  select(taxon, COL_sub_01 = "dive 1", COL_sub_02 = "dive 2")

sand_and_pebbles_dacor <- sand_and_pebbles %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "sand with pebbles") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme) %>% 
  arrange(desc(dacor_num))
```

### Boulders

```{r}
boulders_ES_AMF <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub", "files/navigator_annotations_sala_friedlander.xlsx"), 
                                    sheet = "boulder with ledges") %>% 
  janitor::clean_names() %>% 
  select(taxon, COL_sub_01 = "dive_1", COL_sub_03 = "dive_3") %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "boulder") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)


boulders_JM <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/navigator_annotations_mayorga.xlsx"), 
                                 sheet = "boulder with ledges") %>% 
  select(taxon, COL_sub_04 = "dive 4") %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "boulder") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)

boulders_dacor <- boulders_JM %>% 
  bind_rows(boulders_ES_AMF) %>% 
  arrange(desc(dacor_num))
```

### Rock and sand

```{r}
rock_and_sand_ES_AMF <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub", "files/navigator_annotations_sala_friedlander.xlsx"), 
                                         sheet = "mixed rock and sand") %>% 
  janitor::clean_names() %>% 
  select(taxon, COL_sub_01 = "dive_1", COL_sub_03 = "dive_3")

rock_and_sand_ES_AMF %>% 
  janitor::get_dupes(taxon)

rock_and_sand_ES_AMF <- rock_and_sand_ES_AMF %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "rock and sand") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)
  

rock_and_sand_JM <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/navigator_annotations_mayorga.xlsx"), 
                                      sheet = "mixed rock and sand") %>% 
  select(taxon, COL_sub_04 = "dive 4") %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "rock and sand") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme)

rock_and_sand_dacor <- rock_and_sand_JM %>% 
  bind_rows(rock_and_sand_ES_AMF)%>% 
  arrange(desc(dacor_num))
```

### Sand

```{r}
sand <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/navigator_annotations_mayorga.xlsx"), 
                             sheet = "sand") %>% 
  select(taxon, COL_sub_04 = "dive 4")

sand_dacor <- sand %>% 
  pivot_longer(cols = -taxon, names_to = "ps_station_id", values_to = "dacor") %>% 
  filter(!is.na(dacor)) %>% 
  mutate(dacor_num = dacor_to_num(dacor),
         habitat = "sand") %>% 
  left_join(navi_taxa_lut) %>% 
  filter(!is.na(phylum)) %>% 
  select(ps_station_id, habitat, phylum, taxon, nombre_comun, dacor, dacor_num, is_vme) %>% 
  arrange(desc(dacor_num))
```

### join them all

```{r}
navigator_dacor <- bind_rows(sand_dacor,
                                 rocky_walls_dacor,
                                 boulders_dacor, 
                                 hard_bottom_dacor, 
                                 sand_and_pebbles_dacor,
                                 rock_and_sand_dacor)

navigator_dacor %>% 
  arrange(ps_station_id) %>% 
  write_csv(file.path(ps_exp_path, "data", "secondary", "processed", "COL_sub_navigator_dacor.csv"))
```

```{r}
navigator_dacor %>% 
  ungroup() %>% 
  group_by(habitat) %>% 
  summarize(n_taxa = n_distinct(taxon),
            n_phylum = n_distinct(phylum))
```

```{r}
navigator_dacor %>% 
  ungroup() %>% 
  group_by(habitat, phylum) %>% 
  summarize(n_taxa = n_distinct(taxon),
            n_phylum = n_distinct(phylum))
```

```{r}
navigator_dacor %>% 
  group_by(habitat, phylum) %>% 
  summarize(n_taxa = n_distinct(taxon)) %>% 
  ungroup() %>% 
  mutate(habitat = str_replace_all(habitat, c("boulder" = "montículos de roca",
                                              "hard bottom" = "fondos duros rocosos",
                                              "rock and sand" = "roca y arena",
                                              "rocky walls" = "paredes verticales rocosas",
                                              "sand with pebbles" = "arena y cascajo",
                                              "sand" = "arena"))) %>% 
  ggplot()+
  geom_col(aes(x = fct_reorder(phylum, n_taxa),
               y = n_taxa, 
               fill = n_taxa),
           show.legend = F)+
  coord_flip()+
  facet_wrap("habitat")+
  labs(x = "", y = "Numero de taxones")+
  theme_light()+
  scico::scale_fill_scico(palette = 'roma', direction = -1)
```

## Lengths of H. niphobles

```{r}
niphobles_lengths <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/Hyporthodus_niphobles_lengths.xlsx")) 
  
mean(niphobles_lengths$size_cm)

sd(niphobles_lengths$size_cm)

niphobles_lengths %>% 
  mutate(species = "Hyporthodus niphobles") %>% 
  ggplot()+
  geom_violin(aes(x = species, y = size_cm))+
  geom_jitter(aes(x = species, y = size_cm), height = 0, width = 0.1)+
  labs(x = "", y = "Longitud (cm)", 
       caption = "Distribución de longitud total de individuos observados en el bajo Navegador (mean = 111.0 cm, sd = 33.8 cm)")+
  theme_light()
```

## Bajo Nuevo

```{r}
bn_fish_obs <- readxl::read_xlsx(file.path(ps_exp_path, "data/primary/raw",
                                              "sub","files/bajo_nuevo_annotations.xlsx"),
                  sheet = "observations") %>% 
  filter(!is.na(taxa))

bn_fish_obs <- bn_fish_obs %>% 
  mutate(ps_station_id = if_else(ps_station_id == "SEA_sub_01", "COL_sub_19", "COL_sub_19"))
```

```{r}
bn_taxa <- bn_fish_obs %>% 
  distinct(taxa) %>% 
  mutate(clean_taxa = taxadb::clean_names(taxa, lowercase = F))

bn_taxa_resolved <- bdc_query_names_taxadb(bn_taxa$clean_taxa,
                                           replace_synonyms = TRUE,
                                           suggest_names = TRUE,
                                           suggestion_distance = 0.8,
                                           db = "itis",
                                           parallel = TRUE,
                                           ncores = 2,
                                           export_accepted = FALSE) %>% 
  janitor::clean_names() %>% 
  select(original_search, suggested_name, notes, taxon_id, taxon_rank, vernacular_name, 
         kingdom, phylum, class, order, family, genus)
```

```{r}
unresolved_taxa <- bn_taxa_resolved %>% 
  filter(notes == "notFound" | is.na(notes)) 
```

```{r}
unresolved_higher_taxa <- bn_taxa_resolved %>% 
  filter(taxon_rank != "species") 
```

```{r}
get_taxon_hierarchy <- function(sci_name){
  
  taxa_ids <- taxizedb::name2taxid(sci_name) 
  
  hierarchies <- taxizedb::classification(taxa_ids) %>% 
    set_names(sci_name) %>% 
    unclass() %>% 
    bind_rows(.id = 'id' ) %>% 
    filter(rank %in% c("genus", "family", "order", "class", "phylum", "kingdom")) %>% 
    pivot_wider(names_from = rank, values_from = name, id_cols = id) %>% 
    rename("original_search" = id)

  return(hierarchies)
  
}

tmp <- get_taxon_hierarchy(unresolved_higher_taxa$original_search)
```

```{r}
# resource from: https://alistaire.rbind.io/blog/coalescing-joins/
coalesce_join <- function(x, y, 
                          by = NULL, suffix = c(".x", ".y"), 
                          join = dplyr::full_join, ...) {
  
    joined <- join(x, y, by = by, suffix = suffix, ...)
    # names of desired output
    cols <- union(names(x), names(y))
    
    to_coalesce <- names(joined)[!names(joined) %in% cols]
    suffix_used <- suffix[ifelse(endsWith(to_coalesce, suffix[1]), 1, 2)]
    # remove suffixes and deduplicate
    to_coalesce <- unique(substr(
        to_coalesce, 
        1, 
        nchar(to_coalesce) - nchar(suffix_used)
    ))
    
    coalesced <- purrr::map_dfc(to_coalesce, ~dplyr::coalesce(
        joined[[paste0(.x, suffix[1])]], 
        joined[[paste0(.x, suffix[2])]]
    ))
    names(coalesced) <- to_coalesce
    
    dplyr::bind_cols(joined, coalesced)[cols]
}

bn_taxa_resolved <- bn_taxa_resolved %>% 
  coalesce_join(tmp, by = "original_search")
```

```{r}
bn_taxa <- bn_taxa %>% 
  left_join(bn_taxa_resolved, 
            by = c("clean_taxa" = "original_search"))

bn_taxa <- bn_taxa %>% 
  mutate(sci_name = coalesce(suggested_name, taxa),
         vernacular_name = str_to_sentence(vernacular_name)) %>% 
  select(taxa, sci_name, vernacular_name, taxon_id, kingdom, phylum, class, order, family, genus)
```


```{r}
navi_taxa_lut


navi_taxa_resolved <- bdc_query_names_taxadb(taxadb::clean_names(navi_taxa_lut$taxon,
                                                                 lowercase = F),
                                           replace_synonyms = TRUE,
                                           suggest_names = TRUE,
                                           suggestion_distance = 0.8,
                                           db = "itis",
                                           parallel = TRUE,
                                           ncores = 2,
                                           export_accepted = FALSE) %>% 
  janitor::clean_names() %>% 
  select(original_search, suggested_name, notes, taxon_id, taxon_rank, vernacular_name, 
         kingdom, phylum, class, order, family, genus)
```

