---
title: "Process YSI"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
library(raster)
library(sf)
library(tidyverse)
library(ggspatial)
library(lubridate)
library(bdc)
source("_prj_vars.R")
load(file = file.path(ps_exp_path, "data", "secondary", "processed", "admin_spatial_layers.RData"))
```


# Profiles

```{r}
ysi_data <- ysi_data %>% 
  left_join(ysi_metadata %>% 
              select(ps_station_id,location, sublocation)) 

ysi_data <- ysi_data %>% 
  filter(depth_m > 1,ps_station_id != "COL_ysi_01", odo_percent_sat > 0, chlorophyll_ug_l < 10)
```

## DO

```{r}
ysi_do_plot <- ysi_data %>% 
  group_by(location, ps_station_id) %>% 
  arrange(time) %>% 
  mutate(flag = cumsum(ifelse(depth_m < max(depth_m), 1, NA))) %>% 
  filter(!is.na(flag)) %>% 
  ggplot()+
  geom_line(aes(x = -depth_m, 
                y =  odo_percent_sat, 
                col = location,
                group  = ps_station_id), show.legend = F)+
  coord_flip()+
  facet_wrap(~ location)+
  paletteer::scale_color_paletteer_d("rcartocolor::Vivid")+
  theme_light()+
  labs(y = "Dissolved Oxygen (% DO)",  x  = "Depth (m)")

ggsave(plot = ysi_do_plot,
       filename = file.path(ps_exp_path, "figures", "ysi_do.png"), 
       dpi = 300)
```

## CHL-a

```{r}
ysi_chla_plot <- ysi_data %>% 
  group_by(location, ps_station_id) %>% 
  arrange(time) %>% 
  mutate(flag = cumsum(ifelse(depth_m < max(depth_m), 1, NA))) %>% 
  filter(!is.na(flag)) %>% 
  ggplot()+
  geom_line(aes(x = -depth_m, 
                y =  chlorophyll_ug_l, 
                col = location,
                group  = ps_station_id), show.legend = F)+
  coord_flip()+
  facet_wrap(~ location)+
  paletteer::scale_color_paletteer_d("rcartocolor::Vivid")+
  theme_light()+
  labs(y = "Chlorophyl (ug/l)",  x  = "Depth (m)")

ggsave(plot = ysi_chla_plot,
       filename = file.path(ps_exp_path, "figures", "ysi_chla.png"), 
       dpi = 300)
```

## pH

```{r}
ysi_ph_plot <- ysi_data %>% 
  group_by(location, ps_station_id) %>% 
  arrange(time) %>% 
  mutate(flag = cumsum(ifelse(depth_m < max(depth_m), 1, NA))) %>% 
  filter(!is.na(flag)) %>% 
  ggplot()+
  geom_line(aes(x = -depth_m, 
                y =  ph, 
                col = location,
                group  = ps_station_id), show.legend = F)+
  coord_flip()+
  facet_wrap(~ location)+
  paletteer::scale_color_paletteer_d("rcartocolor::Vivid")+
  theme_light()+
  labs(y = "pH",  x  = "Depth (m)")

ggsave(plot = ysi_ph_plot,
       filename = file.path(ps_exp_path, "figures", "ysi_ph.png"), 
       dpi = 300)
```

## Salinity

```{r}
ysi_sal_plot <- ysi_data %>% 
  group_by(location, ps_station_id) %>% 
  arrange(time) %>% 
  mutate(flag = cumsum(ifelse(depth_m < max(depth_m), 1, NA))) %>% 
  filter(!is.na(flag)) %>% 
  ggplot()+
  geom_line(aes(x = -depth_m, 
                y =  sal_psu, 
                col = location,
                group  = ps_station_id), show.legend = F)+
  coord_flip()+
  facet_wrap(~ location)+
  paletteer::scale_color_paletteer_d("rcartocolor::Vivid")+
  theme_light()+
  labs(y = "Salinity (PSU)",  x  = "Depth (m)")

ggsave(plot = ysi_sal_plot,
       filename = file.path(ps_exp_path, "figures", "ysi_sal.png"), 
       dpi = 300)
```

## Temperature

```{r}
ysi_temp_plot <- ysi_data %>% 
  group_by(location, ps_station_id) %>% 
  arrange(time) %>% 
  mutate(flag = cumsum(ifelse(depth_m < max(depth_m), 1, NA))) %>% 
  filter(!is.na(flag)) %>% 
  ggplot()+
  geom_line(aes(x = -depth_m, 
                y =  temp_f, 
                col = location,
                group  = ps_station_id), show.legend = F)+
  coord_flip()+
  facet_wrap(~ location)+
  paletteer::scale_color_paletteer_d("rcartocolor::Vivid")+
  theme_light()+
  labs(y = "Temperature (Farenheit)",  x  = "Depth (m)")

ggsave(plot = ysi_temp_plot,
       filename = file.path(ps_exp_path, "figures", "ysi_temp.png"), 
       dpi = 300)
```
